config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index new create]
  resources :subs, except: [:destroy]
  resources :posts, only: %i[new create edit update show]
  resource :session, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  validates :title, :author_id, presence: true

  belongs_to :author, foreign_key: :author_id, class_name: :User

  has_many :post_subs,
           foreign_key: :post_id,
           class_name: :PostSub,
           dependent: :destroy

  has_many :subs, through: :post_subs, source: :sub
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint           not null, primary key
#  sub_id     :bigint           not null
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class PostSub < ApplicationRecord
  belongs_to :sub, foreign_key: :sub_id, class_name: :Sub

  belongs_to :post, foreign_key: :post_id, class_name: :Post
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
  validates :title, :moderator_id, presence: true

  belongs_to :moderator, foreign_key: :moderator_id, class_name: :User

  has_many :posts, foreign_key: :sub_id, class_name: :Post

  has_many :post_subs,
           foreign_key: :sub_id,
           class_name: :PostSub,
           dependent: :destroy

  has_many :posts, through: :post_subs, source: :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :session_token, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :subs,
           foreign_key: :moderator_id,
           class_name: :Sub,
           dependent: :destroy

  has_many :posts,
           foreign_key: :author_id,
           class_name: :Post,
           dependent: :destroy

  after_initialize :ensure_session_token
  attr_reader :password
  # SPIREg

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def password(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  private

  def generate_session_token
    token = SecureRandom.urlsafe_base64
    token = SecureRandom.urlsafe_base64 while User.exists?(
      session_token: token,
    )
    token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||=
      User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
    @current_user = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, only: %i[new create edit update]
  before_action :set_post, only: %i[edit update show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @post.author_id == current_user.id && @post.update(post_params)
      redirect_to posts_url
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    if @post
      render :show
    else
      redirect_to subs_url
    end
  end

  private

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    user =
      User.find_by_credentials(
        params[:user][:username],
        params[:user][:password],
      )
    @user = User.new(user_params)

    if user
      login!(user)
      redirect_to poems_url
    else
      flash[:errors] = ['Invalid username or password']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, only: %i[new create edit update]

  def index
    @subs = Sub.all
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
  end

  def edit
    @sub = current_user.subs.find_by(id: params[:id])
    render :edit
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      render :show
    else
      redirect_to subs_url
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.moderator_id == current_user.id && @sub.update(sub_params)
      redirect_to subs_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: %i[index show]

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to users_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <% if logged_in? %>
        <form action="<%= session_url%>" method="POST">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="DELETE">
          <button>Sign Out</button>
        </form>
      <% end %>
      <%= yield %>
  
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
  </body>
</html>

app/views/posts/_form.html.erb
<% url = action == :new ? posts_url : post_url(post) %>
<% button_value = action == :new ? "Create Post" : "Save Edited Post" %>
<form action = "<%= url  %>" method="POST">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title:
    <input type="text" name="post[title]" value ="<%= @post.title  %>">
  </label>
  <br>
  <label>URL:
    <input type="text" name="post[url]" value ="<%= @post.url %>">
  </label>
  <br>
  <label>Content
    <textarea name="post[content]"><%= @post.content %></textarea>
  </label>
  <button><%= button_value %></button>
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form', post: @post, action: :edit %>

app/views/posts/new.html.erb
<h2>Make a New Post</h2>
<%= render 'form', post: @post, action: :new %>

app/views/posts/show.html.erb
<% post_author = @post.author %>

<h2><%= @post.title %> by <%= post_author.username %></h2>

<p>URL: <%= @post.url %></p>

<p><%= @post.content %></p>


<% if logged_in? && @post.author_id == current_user.id %>
    <a href="<%= edit_post_url(@post) %>">Edit Post</a>
<% end %>

app/views/subs/_form.html.erb
<% url = action == :new ? subs_url : sub_url(sub) %>
<% button_value = action == :new ? "Create Sub" : "Save Edited Sub" %>
<form action = "<%= url  %>" method="POST">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title:
    <input type="text" name="sub[title]" value ="<%= @sub.title  %>">
  </label>
  <br>
  <label>Description:
    <input type="text" name="sub[description]" value ="<%= @sub.description  %>">
  </label>
  <br>
  <button><%= button_value %></button>
</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render 'form', sub: @sub, action: :edit %>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  <% @subs.each do |sub| %>
    <a href="<%= sub_url(sub)%>">
      <%= sub.title %>
    </a>
    <br>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>
<%= render 'form', sub: @sub, action: :new %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p><%= @sub.description %></p>
<% if logged_in %>
  <a href="<%= new_post_url %>">
    Make a new Post!
  </a>
<% end %>
<h3>Posts:</h3>
<ul>
  <% posts.each do |post| %>
    <li>
      <a href="<%= post_url(post) %>">
        <%= post.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <a href="<%= user_url(user)%>">
      <li><%= user.username %></li>
    </a>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
  <label>Username:
    <input type="text" name="user[username]" value="<%= @user.username%>">
  </label>
  <label>Password:
    <input type="password" name="user[password]" value="<%= @user.password%>">
  </label>
  <button>Sign Up</button>
</form>